package bibleref

// bookNames maps book number (1-66) to its English name followed by accepted
// abbreviations (lowercase, no periods). The parser also accepts any
// unambiguous prefix of the full name.
var bookNames = [67][]string{
	{},
	{"Genesis", "ge", "gen"},
	{"Exodus", "ex", "exod"},
	{"Leviticus", "le", "lev"},
	{"Numbers", "nu", "num"},
	{"Deuteronomy", "de", "deut", "dt"},
	{"Joshua", "jos", "josh"},
	{"Judges", "jg", "judg"},
	{"Ruth", "ru"},
	{"1 Samuel", "1sa", "1sam", "1sm"},
	{"2 Samuel", "2sa", "2sam", "2sm"},
	{"1 Kings", "1ki", "1kgs"},
	{"2 Kings", "2ki", "2kgs"},
	{"1 Chronicles", "1ch", "1chr", "1chron"},
	{"2 Chronicles", "2ch", "2chr", "2chron"},
	{"Ezra", "ezr"},
	{"Nehemiah", "ne", "neh"},
	{"Esther", "es", "esth"},
	{"Job", "job"},
	{"Psalms", "ps", "psalm", "psa", "pss"},
	{"Proverbs", "pr", "prov"},
	{"Ecclesiastes", "ec", "eccl", "ecc"},
	{"Song of Solomon", "ca", "song", "sos", "canticles"},
	{"Isaiah", "isa", "is"},
	{"Jeremiah", "jer", "je"},
	{"Lamentations", "la", "lam"},
	{"Ezekiel", "eze", "ezek", "ezk"},
	{"Daniel", "da", "dan", "dn"},
	{"Hosea", "ho", "hos"},
	{"Joel", "joe", "joel", "jl"},
	{"Amos", "am", "amos"},
	{"Obadiah", "ob", "obad"},
	{"Jonah", "jon"},
	{"Micah", "mic", "mi"},
	{"Nahum", "na", "nah"},
	{"Habakkuk", "hab"},
	{"Zephaniah", "zep", "zeph"},
	{"Haggai", "hag"},
	{"Zechariah", "zec", "zech"},
	{"Malachi", "mal"},
	{"Matthew", "mt", "matt", "mat"},
	{"Mark", "mr", "mark", "mk"},
	{"Luke", "lu", "luke", "lk"},
	{"John", "joh", "john", "jn"},
	{"Acts", "ac", "acts"},
	{"Romans", "ro", "rom"},
	{"1 Corinthians", "1co", "1cor"},
	{"2 Corinthians", "2co", "2cor"},
	{"Galatians", "ga", "gal"},
	{"Ephesians", "eph"},
	{"Philippians", "php", "phil"},
	{"Colossians", "col"},
	{"1 Thessalonians", "1th", "1thess", "1thes"},
	{"2 Thessalonians", "2th", "2thess", "2thes"},
	{"1 Timothy", "1ti", "1tim"},
	{"2 Timothy", "2ti", "2tim"},
	{"Titus", "tit", "ti"},
	{"Philemon", "phm", "phlm"},
	{"Hebrews", "heb"},
	{"James", "jas", "jam"},
	{"1 Peter", "1pe", "1pet"},
	{"2 Peter", "2pe", "2pet"},
	{"1 John", "1jo", "1john", "1jn"},
	{"2 John", "2jo", "2john", "2jn"},
	{"3 John", "3jo", "3john", "3jn"},
	{"Jude", "jude", "jud"},
	{"Revelation", "re", "rev"},
}
